title: Mezmer
description: A home for OP-XY visualisations
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
github:
  app_url: https://github.com/idroz/mezmer-app/releases/download/latest/Mezmer.zip